run:
  timeout: 5m
issues:
  fix: true
linters:
  enable-all: true
  disable:
  # deprecated linters
  - nosnakecase
  - deadcode
  - scopelint
  - interfacer
  - structcheck
  - ifshort
  - varcheck
  - golint
  ####################
  - gochecknoglobals
  - exhaustivestruct
  - exhaustruct
  - varnamelen
  - musttag
  - depguard
  - maligned