FROM golang:1.24-alpine AS builder
WORKDIR /app/
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o pod-admission-controller ./cmd

FROM alpine:latest

WORKDIR /app/

RUN apk upgrade \
&& addgroup -g 30626 -S app \
&& adduser -u 30626 -D -S -G app app

COPY --from=0 /app/pod-admission-controller /app/pod-admission-controller

USER 30626

ENTRYPOINT [ "/app/pod-admission-controller" ]