replicas: 1

pdb:
  enabled: false
  minAvailable: 1

registry:
  image: paskalmaksim/pod-admission-controller:latest
  imagePullPolicy: Always

env: []
args: []

resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 100m
    memory: 200Mi

tolerations: []
# - key: "kubernetes.azure.com/scalesetpriority"
#   operator: "Equal"
#   value: "spot"
#   effect: "NoSchedule"

# application config
config: ""

extraVolumes: []
extraVolumeMounts: []

# certificates for dev purpuses, generate new certificates
certificates:
  caCert: |
    -----BEGIN CERTIFICATE-----
    MIIDizCCAnOgAwIBAgIBATANBgkqhkiG9w0BAQsFADBWMQswCQYDVQQGEwJVUzEc
    MBoGA1UEChMTZW52b3ktY29udHJvbC1wbGFuZTELMAkGA1UECxMCQ0ExHDAaBgNV
    BAMTE2Vudm95LWNvbnRyb2wtcGxhbmUwHhcNMjIwNTAzMTcyMjA4WhcNMzAwNzIw
    MTcyMjE4WjBWMQswCQYDVQQGEwJVUzEcMBoGA1UEChMTZW52b3ktY29udHJvbC1w
    bGFuZTELMAkGA1UECxMCQ0ExHDAaBgNVBAMTE2Vudm95LWNvbnRyb2wtcGxhbmUw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQClJwqarnYY/At0VsfWJXbU
    RK9Bm4Sd6tGroEJPt+3HHnqFt3ucOjwPR2G7yDBIOEki4bcNvMjxnVV7y8AYGZF3
    S0ruQnflFd/CE9qePLC0Q8PeG8oeIFz1wge+dGZkrLG/xQ8oiVuJ5DqWBEmBl2nF
    ZG7TgEKHsdCB5sYhNn4WpEzsyyWZAPhRA46eesaTkH027EWav7GcfsLeeAxBfjwP
    FIFsmkrMtgelbC0CW1YRrwR/oagU+GGRyju72K04WCaAULlVECF5HJ0xTmDvNlph
    vfdXMqvIDDX9KUR8KJojzb1ItdIaPg7tsSrZADDVAfMO4sYjubF9o1XukGOyPS5J
    AgMBAAGjZDBiMA4GA1UdDwEB/wQEAwIBBjAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
    KwYBBQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBAjAdBgNVHQ4EFgQUbg14n0/2Hkuf
    IxzH8aagk3zXWMMwDQYJKoZIhvcNAQELBQADggEBAEloWHhSlBJ26ujjKiCLsdG+
    sMkGiPvfRDtFazA+2cfHhZyQwStP74U0FOA3yrpXLsY+XpjsncSQEFGG3buBhpcw
    lNBh4s5L4CbP4DEqSPe7TnUVttf2xrW2GwRUFBte+/OuhF68Yy5SA4Vx1VV7rboU
    Cb51aVhOQEuAa8ySdGdc3cQwzA0O3MBBatqphloZZTcedEJAByBuvjJz8nRo36mU
    rDGU7oVBbyAUFuzd55cI7Ui2VbQXDiFk/GsLSK+5SKGOXlq/NE61KeWI/LQxVLMN
    sUQEbTa61x8Aq+mNP5F2YZ44wc/q/o3PNstS/Q/RLEkWnLr94GHykslfhd81BVE=
    -----END CERTIFICATE-----
  serverCrt: |
    -----BEGIN CERTIFICATE-----
    MIIELDCCAxSgAwIBAgIEYnFkyjANBgkqhkiG9w0BAQsFADBWMQswCQYDVQQGEwJV
    UzEcMBoGA1UEChMTZW52b3ktY29udHJvbC1wbGFuZTELMAkGA1UECxMCQ0ExHDAa
    BgNVBAMTE2Vudm95LWNvbnRyb2wtcGxhbmUwHhcNMjIwNTAzMTcyMjA4WhcNMzAw
    NzIwMTcyMjE4WjB8MQswCQYDVQQGEwJVUzEcMBoGA1UEChMTZW52b3ktY29udHJv
    bC1wbGFuZTEPMA0GA1UECxMGQ0xJRU5UMT4wPAYDVQQDEzVwb2QtYWRtaXNzaW9u
    LWNvbnRyb2xsZXIucG9kLWFkbWlzc2lvbi1jb250cm9sbGVyLnN2YzCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBANbmJqjVdi78QPb2s5/FiQbtfHFb/94E
    1U0oW74hgTinL374RgMR+B72iN63K9VVSlyDoNcRuuZEmDwgavE6b8UQR84138t+
    WhFcWDQcLxbzfJAjjiuiJlC+Z8Ww+K2NU/8YxQ4C9DOZM1fMq2K76EbuBJ1r+NJE
    fdOBH7TXAsmFG1XSokvM1VWR+FjKdrwxpta7RAtwCUmv2c70a8H3bBlocDERIprK
    s5Y/ytMqixHuOfMrEK/NByYmnSVZab8lC3gUEDyufoIqB7CaOVlKeYBzEgEEKmuI
    rbBzq0EKXMEYcuV9kcT9paddE4LQS/pP4mFYYSrcgDt694ILosGuIGMCAwEAAaOB
    2zCB2DAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
    BwMCMB8GA1UdIwQYMBaAFG4NeJ9P9h5LnyMcx/GmoJN811jDMIGFBgNVHREEfjB8
    gjVwb2QtYWRtaXNzaW9uLWNvbnRyb2xsZXIucG9kLWFkbWlzc2lvbi1jb250cm9s
    bGVyLnN2Y4JDcG9kLWFkbWlzc2lvbi1jb250cm9sbGVyLnBvZC1hZG1pc3Npb24t
    Y29udHJvbGxlci5zdmMuY2x1c3Rlci5sb2NhbDANBgkqhkiG9w0BAQsFAAOCAQEA
    pFBe/3sYlO9CpoAw7jG7YVLT0W9TbHUc/HsgelGr5S7dAC6tec0KDzmsUwwvq0uo
    k19h4+AI6VvT/f4Z/m31npd6duLC3X0Ps4o9gjv6PRsvefD3H9QvYSO5AROzvWin
    08pI8EXo1aAk7adLY1ee64TxixU6Sva2RM0cjJ5XirQKEVVOrwVFuIfOZVUcqnhJ
    ++9k/g8+up9L5QtclOoYt40HbpnJXAhrrnE3v8Eaqk4vwbuyUC2orzOgfDSepMH/
    1nLQblV3xA3rOUAElWTBdBg490/x21B/asrdoeuFdLITo5tUg8kwbwjbciAONt8r
    S7i2ulTJ5HSUPjogJ9Tsfg==
    -----END CERTIFICATE-----
  serverKey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDW5iao1XYu/ED2
    9rOfxYkG7XxxW//eBNVNKFu+IYE4py9++EYDEfge9ojetyvVVUpcg6DXEbrmRJg8
    IGrxOm/FEEfONd/LfloRXFg0HC8W83yQI44roiZQvmfFsPitjVP/GMUOAvQzmTNX
    zKtiu+hG7gSda/jSRH3TgR+01wLJhRtV0qJLzNVVkfhYyna8MabWu0QLcAlJr9nO
    9GvB92wZaHAxESKayrOWP8rTKosR7jnzKxCvzQcmJp0lWWm/JQt4FBA8rn6CKgew
    mjlZSnmAcxIBBCpriK2wc6tBClzBGHLlfZHE/aWnXROC0Ev6T+JhWGEq3IA7eveC
    C6LBriBjAgMBAAECggEAM4iVlL87zCCp449dm97e8U5aHUUWosM983bOKVYXiuJs
    vWIESBAzFBnC0MXUOSBu6KiYFXsm+rlQWHrdqmN9EiDJV2YL+Nyf9LHUZQqtMC/L
    mzUrjsMftRU0BXBe8h+GGRJzjtyeexEuAswN/WtaVEgXyzhtPt813VaFp/Q3suNM
    H9s2zN76hjQsJOzPrhCI1RAkhhheSJv9+vs017OnCt8HxCclmXYo/cCfzrS58FTX
    X1E5hTgD3pmxg9BOWf0ayd7Z2tHkcn73oZH3dHfd1pZMRnYO09/O+JguwWF+mjGq
    9wKZ+ibKO4gUSfAnNYuqqkreZ9Vp5OIlDwYmJO0pQQKBgQDpJy2WATz40yioJKmJ
    oWoAYVugBsQN1TS63g0Z7OahJ2MECmjJWMdD09bKHzgl0G+0MpysKncDuqvAZvZj
    oyM+Oc50P3m3WMiZm2iRf6C48j7aSrNBK70iJYhqbXCOd3iMgQJmK6US7ygq6uFj
    BZGTtJcHjkIUDmBZ9Kwh7doTSQKBgQDr9Q6fm9ksHIcd4ol+GKBQS6hUXEr1P8wi
    JoIRvG2pSJSX8xJDvw1+8Ts8ycP+W0A81uUq4far7+rt/FItnz27qu0hmRCQGRna
    fpdZKqno+kvjUnVQCOPutE6gpXdF64jAInO59ClkvxNbGxYM5Q8ZFZEwIM8KeBk3
    LBt19hyqSwKBgQCWBQB/CbLqxCvf7R8tkK/9KKflExVpdStlpeU2LknDne1HN09v
    ZvFoglEtYuMk6bZGc15+JSDJRH6o4VdeiyTtMBLYl9NAlx8UP3wMStvmxPCOUwx+
    PZ+H7jCVkm+fK95kQcqCZUjlIv9shg+aQIYITWX0laOM9icnGpj7h+kPCQKBgAta
    Gd8B73vYz4NXj8faRXQ3f5y3Z//OlvKZqa5Sw2/ehw+caSeLPIn77x6okl5dY4TJ
    zfK3NlflTgcvGYEKZTzvJ0NzisF0A7NoXb2zeMM1r4r7P5ufIeAtGo9OBqP9hfHA
    dpLetVMcgkDi17e9GXHagMaw/WUCjCwEWjndollrAoGASar1XrShyXQpB6YoVi3g
    aMDLeYQdZ023kUjsuEL+kiESSqfAeBq+DtlYLRxt+RKiAFqlke1w7Vp56oK5aceu
    OXU4sKHAAvORwLQ6oXKPtTnP+9ivJYmQuMitYqaGZ/tsylkXujRIaHhL9uVhwTJ8
    JLjH1Gt+UVJQ2CXl2rP1ITk=
    -----END PRIVATE KEY-----

webhook:
  caBundle: "{{ b64enc .Values.certificates.caCert }}"
  # Fail/Ignore
  failurePolicy: Ignore
  namespaceSelector:
  - key: environment
    operator: In
    values:
    - dev
    - stage
    - prod
