apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-admission-controller
  labels:
    app: pod-admission-controller
webhooks:
- name: pod-admission-controller.pod-admission-controller.svc.cluster.local
  failurePolicy: Ignore
  clientConfig:
    caBundle: {{ tpl .Values.webhook.caBundle . | quote }}
    service:
      name: pod-admission-controller
      namespace: pod-admission-controller
      path: "/mutate"
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
  namespaceSelector:
    matchExpressions:
{{ toYaml .Values.webhook.namespaceSelector | indent 4 }}