apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-admission-controller
  labels:
    app: pod-admission-controller
webhooks:
- name: pod-admission-controller.pod-admission-controller.svc.cluster.local
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  clientConfig:
    caBundle: {{ tpl .Values.webhook.caBundle . | quote }}
    service:
      name: pod-admission-controller
      namespace: pod-admission-controller
      path: "/mutate"
  rules:
  - operations: ["CREATE","UPDATE"]
    apiGroups: ["networking.k8s.io"]
    apiVersions: ["v1"]
    resources: ["ingresses"]
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  # create operation for namespace doesn't work,
  # because secret creation requires namespace to exist
  - operations: ["UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["namespaces"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
  namespaceSelector:
    matchExpressions:
{{ toYaml .Values.webhook.namespaceSelector | indent 4 }}