on: pull_request

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k3s_version: ["v1.27.8+k3s2","v1.28.4+k3s2","v1.29.1+k3s2"]
        helm_version: ["v3.8.1"]
    steps:
    - name: Setup Kubernetes
      run: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="${{ matrix.k3s_version }}" K3S_KUBECONFIG_MODE=777 sh -
    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: ${{ matrix.helm_version }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Build
      run: go run github.com/goreleaser/goreleaser@latest build --clean --snapshot --skip=validate
    - name: Copy binary
      run: mv ./dist/pod-admission-controller_linux_amd64_v1/pod-admission-controller ./pod-admission-controller
    - name: Test binary
      run: ./pod-admission-controller -version
    - name: Run tests
      run: make e2e KUBECONFIG=/etc/rancher/k3s/k3s.yaml image=alpine:latest helm_args="--values=./e2e/values.github.yaml --values=./e2e/values.yaml"