on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - run: make test
    - uses: codecov/codecov-action@v3